INSERT INTO player (`name`, `team`, `age`, `hometown`, `height`, `weight`, `yearsOfExp`, `jerseyNumber`, `position`, `createdBy`) VALUES ('Joel Anthony', 'Boston Celtics', '32', 'Montreal, Canada', '6-9', '245', '6', '50', 'C', 'Admin');
INSERT INTO player (`name`, `team`, `age`, `hometown`, `height`, `weight`, `yearsOfExp`, `jerseyNumber`, `position`, `createdBy`) VALUES ('Chris Babb', 'Boston Celtics', '25', 'Arlington, Texas', '6-5', '225', '1', '52', 'SG', 'Admin');
INSERT INTO player (`name`, `team`, `age`, `hometown`, `height`, `weight`, `yearsOfExp`, `jerseyNumber`, `position`, `createdBy`) VALUES ('Brandon Bass', 'Boston Celtics', '30', 'Baton Rouge, Lousiana', '6-8', '240', '8', '30', 'PF', 'Admin');
INSERT INTO player (`name`, `team`, `age`, `hometown`, `height`, `weight`, `yearsOfExp`, `jerseyNumber`, `position`, `createdBy`) VALUES ('Jerryd Bayless', 'Boston Celtics', '27', 'Phoenix, Arizona', '6-3', '200', '5', '11', 'PG', 'Admin');
INSERT INTO player (`name`, `team`, `age`, `hometown`, `height`, `weight`, `yearsOfExp`, `jerseyNumber`, `position`, `createdBy`) VALUES ('Vander Blue', 'Boston Celtics', '23', 'Milwaukee, Wisconsin', '6-4', '200', '1', '13', 'SG', 'Admin');
INSERT INTO player (`name`, `team`, `age`, `hometown`, `height`, `weight`, `yearsOfExp`, `jerseyNumber`, `position`, `createdBy`) VALUES ('Keith Bogans', 'Boston Celtics', '35', 'Alexandria, Virginia', '6-5', '215', '10', '4', 'SG', 'Admin');
INSERT INTO player (`name`, `team`, `age`, `hometown`, `height`, `weight`, `yearsOfExp`, `jerseyNumber`, `position`, `createdBy`) VALUES ('Avery Bradley', 'Boston Celtics', '25', 'Tacoma, Washington', '6-2', '180', '3', '0', 'PG', 'Admin');
INSERT INTO player (`name`, `team`, `age`, `hometown`, `height`, `weight`, `yearsOfExp`, `jerseyNumber`, `position`, `createdBy`) VALUES ('MarShon Brooks', 'Boston Celtics', '26', 'Long Branch, New Jersey', '6-5', '200', '2', '12', 'SG', 'Admin');
INSERT INTO player (`name`, `team`, `age`, `hometown`, `height`, `weight`, `yearsOfExp`, `jerseyNumber`, `position`, `createdBy`) VALUES ('Jordan Crawford', 'Boston Celtics', '27', 'Detroit, Michigan', '6-4', '195', '3', '27', 'SG', 'Admin');
INSERT INTO player (`name`, `team`, `age`, `hometown`, `height`, `weight`, `yearsOfExp`, `jerseyNumber`, `position`, `createdBy`) VALUES ('Vitor Faverani', 'Boston Celtics', '27', 'Porto, Alegre', '6-11', '260', '1', '38', 'C', 'Admin');
INSERT INTO player (`name`, `team`, `age`, `hometown`, `height`, `weight`, `yearsOfExp`, `jerseyNumber`, `position`, `createdBy`) VALUES ('Jeff Green', 'Boston Celtics', '29', 'Cheverly, Maryland', '6-9', '235', '5', '8', 'SF', 'Admin');
INSERT INTO player (`name`, `team`, `age`, `hometown`, `height`, `weight`, `yearsOfExp`, `jerseyNumber`, `position`, `createdBy`) VALUES ('Kris Humphries', 'Boston Celtics', '30', 'Minneapolis, Minnesota', '6-9', '235', '9', '43', 'PF', 'Admin');
INSERT INTO player (`name`, `team`, `age`, `hometown`, `height`, `weight`, `yearsOfExp`, `jerseyNumber`, `position`, `createdBy`) VALUES ('Chris Johnson', 'Boston Celtics', '25', 'Orlando, Florida', '6-6', '201', '1', '12', 'SF', 'Admin');
INSERT INTO player (`name`, `team`, `age`, `hometown`, `height`, `weight`, `yearsOfExp`, `jerseyNumber`, `position`, `createdBy`) VALUES ('Courtney Lee', 'Boston Celtics', '30', 'Indianapolis, Indiana', '6-5', '200', '5', '11', 'SG', 'Admin');
INSERT INTO player (`name`, `team`, `age`, `hometown`, `height`, `weight`, `yearsOfExp`, `jerseyNumber`, `position`, `createdBy`) VALUES ('Kelly Olynyk', 'Boston Celtics', '24', 'Toronto, Canada', '7-0', '238', '1', '41', 'C', 'Admin');
INSERT INTO player (`name`, `team`, `age`, `hometown`, `height`, `weight`, `yearsOfExp`, `jerseyNumber`, `position`, `createdBy`) VALUES ('Phil Pressey', 'Boston Celtics', '24', 'Dallas, Texas', '5-11', '175', '1', '26', 'PG', 'Admin');
INSERT INTO player (`name`, `team`, `age`, `hometown`, `height`, `weight`, `yearsOfExp`, `jerseyNumber`, `position`, `createdBy`) VALUES ('Rajon Rondo', 'Boston Celtics', '29', 'Louisville, Kentucky', '6-1', '171', '7', '9', 'PG', 'Admin');
INSERT INTO player (`name`, `team`, `age`, `hometown`, `height`, `weight`, `yearsOfExp`, `jerseyNumber`, `position`, `createdBy`) VALUES ('Jared Sullinger', 'Boston Celtics', '22', 'Columbus, Ohio', '6-9', '280', '1', '7', 'PF', 'Admin');
INSERT INTO player (`name`, `team`, `age`, `hometown`, `height`, `weight`, `yearsOfExp`, `jerseyNumber`, `position`, `createdBy`) VALUES ('Gerald Wallace', 'Boston Celtics', '32', 'Sylacauga, Alabama', '6-7', '215', '12', '45', 'SF', 'Admin');

INSERT INTO basketball (`pointsPerGame`, `assistsPerGame`, `reboundsPerGame`, `bk_playerID`) VALUES ('1', '0.1', '1.5', '1');
INSERT INTO basketball (`pointsPerGame`, `assistsPerGame`, `reboundsPerGame`, `bk_playerID`) VALUES ('1.6', '0.2', '1.2', '2');
INSERT INTO basketball (`pointsPerGame`, `assistsPerGame`, `reboundsPerGame`, `bk_playerID`) VALUES ('11.1', '1.1', '5.7', '3');
INSERT INTO basketball (`pointsPerGame`, `assistsPerGame`, `reboundsPerGame`, `bk_playerID`) VALUES ('10.1', '3.1', '2.1', '4');
INSERT INTO basketball (`pointsPerGame`, `assistsPerGame`, `reboundsPerGame`, `bk_playerID`) VALUES ('1.7', '0.3', '1', '5');
INSERT INTO basketball (`pointsPerGame`, `assistsPerGame`, `reboundsPerGame`, `bk_playerID`) VALUES ('2', '0.5', '0.5', '6');
INSERT INTO basketball (`pointsPerGame`, `assistsPerGame`, `reboundsPerGame`, `bk_playerID`) VALUES ('14.9', '1.4', '3.8', '7');
INSERT INTO basketball (`pointsPerGame`, `assistsPerGame`, `reboundsPerGame`, `bk_playerID`) VALUES ('3.1', '0.4', '1.9', '8');
INSERT INTO basketball (`pointsPerGame`, `assistsPerGame`, `reboundsPerGame`, `bk_playerID`) VALUES ('13.7', '5.7', '3.1', '9');
INSERT INTO basketball (`pointsPerGame`, `assistsPerGame`, `reboundsPerGame`, `bk_playerID`) VALUES ('4.4', '0.4', '3.5', '10');
INSERT INTO basketball (`pointsPerGame`, `assistsPerGame`, `reboundsPerGame`, `bk_playerID`) VALUES ('16.9', '1.7', '4.6', '11');
INSERT INTO basketball (`pointsPerGame`, `assistsPerGame`, `reboundsPerGame`, `bk_playerID`) VALUES ('8.4', '1', '5.9', '12');
INSERT INTO basketball (`pointsPerGame`, `assistsPerGame`, `reboundsPerGame`, `bk_playerID`) VALUES ('6.3', '0.8', '2.4', '13');
INSERT INTO basketball (`pointsPerGame`, `assistsPerGame`, `reboundsPerGame`, `bk_playerID`) VALUES ('7.4', '1.1', '1.6', '14');
INSERT INTO basketball (`pointsPerGame`, `assistsPerGame`, `reboundsPerGame`, `bk_playerID`) VALUES ('8.7', '1.6', '5.2', '15');
INSERT INTO basketball (`pointsPerGame`, `assistsPerGame`, `reboundsPerGame`, `bk_playerID`) VALUES ('2.8', '3.2', '1.4', '16');
INSERT INTO basketball (`pointsPerGame`, `assistsPerGame`, `reboundsPerGame`, `bk_playerID`) VALUES ('11.7', '9.8', '5.5', '17');
INSERT INTO basketball (`pointsPerGame`, `assistsPerGame`, `reboundsPerGame`, `bk_playerID`) VALUES ('13.3', '1.6', '8.1', '18');
INSERT INTO basketball (`pointsPerGame`, `assistsPerGame`, `reboundsPerGame`, `bk_playerID`) VALUES ('5.1', '2.5', '3.7', '19');
